<a href="https://colab.research.google.com/github/PadhAIGroupLearning/padhai-exercises/blob/master/Numpy_Assignments_Questions_200320_184846.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise

#Import Numpy

In [0]:
import numpy as np

# Problem-1
1.   Write a program to multiply two matrices of size $(100, 100)$ in two methods: (a) by using `np.dot(mat_1, mat_2)` and (b) by using for-loops. Comapre the time of execution in both the cases. 

In [0]:
mat_1 = np.ones((100,100)) * 2
mat_2 = np.ones((100,100)) * 2


In [11]:
%%timeit -n10 -r10
prod = np.dot(mat_1, mat_2)


The slowest run took 4.94 times longer than the fastest. This could mean that an intermediate result is being cached.
10 loops, best of 10: 110 µs per loop


In [12]:
%%timeit -n10 -r10
new_mat = np.empty((100,100))
shape_mat1 = mat_1.shape
shape_mat2 = mat_2.shape
for row in range(shape_mat1[0]):
    new_row = np.empty(shape_mat2[1])
    for col in range(shape_mat2[1]):
        new_row[col] = sum(mat_1[row,:] * mat_2[:,col])
    new_mat[row] = new_row


10 loops, best of 10: 211 ms per loop


#Problem-2
2.   Write a program to execute the steps below using numpy:
    $$z_{ij} = \sum_{k=1}^{n}w_{ik}x_{kj}$$
    $$\sigma_{ij}(z_{ij}) = \frac{1}{1+e^{-z_{ij}}}$$ where $\textbf{w}$ and $\textbf{x}$ are matrices of random numbers having  dimensions $(m,n)$ and $(n,k)$, respectively, $\sigma(z)$ is a function which performs above defined operation on elements of $\textbf{z}$.


In [13]:
w = np.random.randint(1,10,(3,4))
x = np.random.randint(1,10,(4,3))
w = np.random.randn(3,4)
x = np.random.randn(4,3)
z = np.dot(w,x)
print (z)
print(1/(1+np.exp(-z)))


[[ 1.49308839 -1.00598245  0.30477325]
 [-0.57953172  1.17082043 -0.2135474 ]
 [-0.64400866  1.04509537 -3.28106499]]
[[0.81654137 0.26776683 0.57560896]
 [0.35904035 0.76329328 0.44681511]
 [0.34434094 0.73983196 0.03622651]]


#Problem-3
3.   Consider a matrix $\textbf{M}$ of size $(n, n)$. Flatten this into a 1-dimensional array and 
> 1. compute **mean** and **standard deviation** of $\textbf{M}$ in *two* ways. <br>
> 2. Apply the element wise operation as defined below: $$z_i = \frac{x_i - \mu}{\sigma}$$ <br> where $x_i, \ \mu,\ \sigma$ are elements, mean and standard deviation of flattened matrix $\textbf{M}$ respectively. And $z$ is the output vector.
> 3. Compute the **mean** and **standard deviation** of $z$ and compare them with the **mean** and **standard deviation** of $\textbf{M}$.
> 4. Resaon about the above comparison.

In [0]:
M = np.random.randint(1,10,(100,100))
shape=M.shape
M=M.reshape(1, shape[0]*shape[1])


In [15]:
mu = np.mean(M)
print(mu)
M.shape

5.0052


(1, 10000)

In [16]:
mean_by_calc = np.sum(M)/(shape[0]*shape[1])
print(mean_by_calc)

5.0052


In [17]:
sigma2 = (M - mu)**2
sigma_by_calc = np.sqrt(np.mean(sigma2))
print(sigma_by_calc)

2.593448083151078


In [18]:
sigma = np.std(M)
print(sigma)

2.593448083151078


In [19]:
z = (M - mu)/sigma
print("mean of z", np.mean(z))
print("stddev of z", np.std(z))


mean of z -1.291411422243982e-16
stddev of z 1.0


Mean of variance has to be 0

and


Std Dev of Variance will be 1

#Problem-4
4.   Consider an $n$ dimentional vector $\vec{V}$ (having $n$ elements), calculate :
> 1. $|\vec{V}|$ (magnitude of vector)
> 2. $\sum_{i=1}^{n}v_i^3$ in three different ways (here $n$ is total number of elements in $\vec{V}$ and $v_i$ is $i_{th}$ element of $\vec{V}$).

In [20]:
V = np.random.randint(1,100,100)
print(V)

[52 81 46 54 48 94 31 61  9 54 72 21 27 65 91 33 26 31 90 22 50 52 65 89
 96 77 57 64 64 16 43  5  3 11 99 20 75 88 57 99 59 38 77  8 95 92 83 84
 79 71 22 17 24 24 42 67  6 87 69  5 42 28 86 65 59 75 34 99 88 53 75 57
  8 99 72 16  8 30 96 15 55 47 71 69 95 43  5 31 63 25 54 35 97 34 13 42
 34 49 34 60]


In [21]:
V_magnitude = np.sqrt((V**2).sum())
print(V_magnitude)

596.7545559105519


In [22]:
V_cube_1 = (V**3).sum()
print(V_cube_1)

27103438


In [23]:
V_cube_2 = (V * V * V).sum()
print(V_cube_2)

27103438


In [24]:
V_cube_3 = np.power(V,3).sum()
print(V_cube_3)

27103438


In [25]:
V_cube_4 = np.dot(V*V,V).sum()
print(V_cube_4)

27103438


#Problem-5

5.   Create two vectors $y$ and $\hat{y}$ having **same** dimensions, where $\hat{y}$ should consist of random numbers between $[0, 1]$ and $y$ should contain $0s$ and $1s$, for example $y = [0, 1, 1, 0, 1, 0, 0, 1, ..., 1]$. Compute the given expression: $$O = -\frac{1}{n}\sum_{i=1}^{n}[y_i\log_2(\hat{y_i}) + (1-y_i)\log_2(1-\hat{y_i})]$$
where $n$ is the total number of elements in $y$ and $\hat{y}$.

In [0]:
shape = 100
y_cap = np.random.rand(shape)
y = np.random.randint(0,2,shape)



In [27]:
temp = -((y * np.log2(y_cap)) +((1-y)*np.log2(1-y_cap)))
print(temp.mean())

1.5546921133106728
