<a href="https://colab.research.google.com/github/PadhAIGroupLearning/padhai-exercises/blob/master/Week8/Wk8_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Compute area outside circle

In [0]:
import numpy as np

In [0]:
def fract_outside_circle(npoints,ndim):
    points_in_square = np.random.rand(npoints,ndim)
    return np.sum(np.sqrt(np.sum((points_in_square * points_in_square),axis=1))>1)/npoints

In [0]:
nPoints = 10**6
for nDim in range(2,11):
    x = fract_outside_circle(nPoints, nDim)
    print(x)

#Exercise on Cricket

1. Find mean, median, IQR for Sachin, Rahul and India
2. Find the histogram of Sachin's scores with 10 bins
3. Find mean of Sachin's scores grouped by 25 matches
4. Find mean of Sachin's scores where he has scored a century
5. Find mean of Sachin's scores when Rahul has scored less than 10 
6. Find mean for Sachin's scores based on which quartile India's score falls in
7. For every match find out who has scored more - Sachin or Rahul
8. How many more runs does Sachin score on average after having scored x runs
9. How many matches did Sachin take to score first 1000, next 1000 ...

In [0]:
#Test array to try out different stat operations
arr2d = np.random.randint(1,10,(5,3))
means = np.mean(arr2d,axis=0)
print(arr2d)
a = arr2d[:, 0]
print(np.size(a))


In [2]:
#This mounts your Google Drive and the filesystem is available to you at /content/drive/My Drive/
#Asks for an authorization, allow it and paste the code.
from google.colab import drive
drive.mount('/content/drive')

#Open the file and read contents, store it in a string called contents
import os
gdrive_path = "/content/drive/My Drive/Colab Notebooks/Week8/"
file = "cric_data-200320-181217.tsv"
full_filename = os.path.join(gdrive_path,file)


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
scores = np.loadtxt(full_filename,skiprows=1, usecols=(1,2,3))
shape_scores = scores.shape

In [4]:
#1. Find mean, median, IQR for Sachin, Rahul and India
means = np.mean(scores, axis = 0)
medians = np.median(scores, axis=0)
percentiles = np.percentile(scores,(25,75),axis=0)
iqr = percentiles[1] - percentiles[0]
print("Mean of Sachin, Rahul and India is ", means)
print("median of Sachin, Rahul and India is ", medians)
print("IQR of Sachin, Rahul and India is", iqr)

Mean of Sachin, Rahul and India is  [ 39.87555556  32.06222222 220.79555556]
median of Sachin, Rahul and India is  [ 27.  22. 216.]
IQR of Sachin, Rahul and India is [57. 46. 98.]


In [22]:
#2. Find the histogram of Sachin's scores with 10 bins
histo_sachin = np.histogram(scores[:,0],bins=10)
print(histo_sachin)


(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]), array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
       167.4, 186. ]))


In [6]:
#3. Find mean of Sachin's scores grouped by 25 matches
score_sachin = scores[:, 0]
sachin_group_by_25 = score_sachin.reshape(-1,25)
means_group_by_25 = np.mean(sachin_group_by_25,axis=1)
print("Sachins's mean in matches grouped by 25 are", means_group_by_25)

Sachins's mean in matches grouped by 25 are [33.96 49.4  38.48 40.16 39.36 38.2  44.6  39.52 35.2 ]


In [7]:
#4. Find mean of Sachin's scores where he has scored a century
sachin_centuries_mean = np.mean(score_sachin[score_sachin>=100])
print("Mean of Sachin's score where he has scored a century ",sachin_centuries_mean)

Mean of Sachin's score where he has scored a century  125.0


In [8]:
#5. Find mean of Sachin's scores when Rahul has scored less than 10
score_rahul = scores[:, 1]
rahul_lessthan10_indices = np.nonzero(score_rahul<10)
print("Mean of Sachin's score when Rahuls has scored less than 10 is", np.mean(score_sachin.take(rahul_lessthan10_indices)))


Mean of Sachin's score when Rahuls has scored less than 10 is 40.74285714285714


In [9]:
#6. Find mean for Sachin's scores based on which quartile India's score falls in
#quartiles = np.percentile(scores,(25,50,75),axis=0)
quartile = np.percentile(scores[:, 2], (25,50,75), axis = 0)

scores_india = scores[:, 2]
indices_india_q1 = np.nonzero(scores_india<quartile[0])
indices_india_q2 = np.nonzero((scores_india>=quartile[0]) & (scores_india<quartile[1]))
indices_india_q3 = np.nonzero((scores_india>=quartile[1]) & (scores_india<quartile[2]))
indices_india_q4 = np.nonzero(scores_india>quartile[2])

print("Mean of Sachin's score when India's score is in it's Q1", np.mean(score_sachin.take(indices_india_q1)))
print("Mean of Sachin's score when India's score is in it's Q2", np.mean(score_sachin.take(indices_india_q2)))
print("Mean of Sachin's score when India's score is in it's Q3", np.mean(score_sachin.take(indices_india_q3)))
print("Mean of Sachin's score when India's score is in it's Q4", np.mean(score_sachin.take(indices_india_q4)))

Mean of Sachin's score when India's score is in it's Q1 19.672727272727272
Mean of Sachin's score when India's score is in it's Q2 36.535714285714285
Mean of Sachin's score when India's score is in it's Q3 38.642857142857146
Mean of Sachin's score when India's score is in it's Q4 63.375


In [10]:
#7. For every match find out who has scored more - Sachin or Rahul
print("Matches where Sachins has score more than Rahul\n", scores[:, 0] > scores[:,1])


Matches where Sachins has score more than Rahul
 [ True False False  True  True False False  True False  True False False
 False  True  True False False False False False  True False  True  True
 False  True  True False  True  True  True  True False False  True False
 False  True False  True  True  True  True False  True False False  True
 False  True False False False False  True False  True  True False False
 False  True False  True  True  True  True False  True False False  True
  True False False  True False False  True False False False False False
 False  True  True  True False  True  True  True False  True  True False
 False  True False  True False False False False False  True False False
  True False False  True False  True False  True  True  True False  True
 False  True  True  True  True False  True False False  True  True False
  True False  True  True  True False  True  True False False False  True
  True  True  True False  True False  True  True  True  True False False
 F

In [40]:
#8. How many more runs does Sachin score on average after having scored x runs
print(len(histo_sachin[1]))
a = np.delete(histo_sachin[1], len(histo_sachin[1])-1)
b = np.delete(histo_sachin[1],0)
print(a)
print(b)
mean_histo = (a + b)/2
print(mean_histo)

current = input("Enter current score of sachin ")

print("Sachin is expected to score",int(mean_histo[mean_histo>int(current)][0]))



11
[  0.   18.6  37.2  55.8  74.4  93.  111.6 130.2 148.8 167.4]
[ 18.6  37.2  55.8  74.4  93.  111.6 130.2 148.8 167.4 186. ]
[  9.3  27.9  46.5  65.1  83.7 102.3 120.9 139.5 158.1 176.7]
Enter current score of sachin 70
Sachin is expected to score 83


In [71]:
#9. How many matches did Sachin take to score first 1000, next 1000 ...
sachin_cumulative = np.cumsum(score_sachin)
max =  int(np.max(sachin_cumulative)/1000)*1000
i= 1000
num_matches_for_every_1000 = []

while(i <= max):
    sachin_cumulative_rounded = np.argmax(sachin_cumulative>i)
    i+=1000
    num_matches_for_every_1000.append(sachin_cumulative_rounded)

num = ["First", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninghth"]

for i in range(len(num_matches_for_every_1000)):
    if i == 0:
        prev = 0
    else:
        prev =  num_matches_for_every_1000[i-1]
    print("Sachin took ",num_matches_for_every_1000[i] - prev, " matches to score the ", num[i], "1000 runs" )




Sachin took  29  matches to score the  First 1000 runs
Sachin took  18  matches to score the  second 1000 runs
Sachin took  26  matches to score the  third 1000 runs
Sachin took  25  matches to score the  fourth 1000 runs
Sachin took  26  matches to score the  fifth 1000 runs
Sachin took  26  matches to score the  sixth 1000 runs
Sachin took  23  matches to score the  seventh 1000 runs
Sachin took  22  matches to score the  eighth 1000 runs
